### PR TITLE
core-suggest: add suggest.expanded event

### PR DESCRIPTION
**Pull request by astokke**

### CODE REVIEW

**Comment by laat** [comment]
```js
  it('emits expanded event when expanded', async () => {
    await browser.executeScript(() => {
      document.body.innerHTML = `
        <input type="text">
        <core-suggest hidden></core-suggest>
      `
    })
    await browser.executeScript(() => {
      const expandedCallback = (event) => { window._expanded = event.detail.expanded }
      document
        .querySelector('core-suggest')
        .addEventListener('suggest.expanded', expandedCallback)
    })
    const lastEmittedExpanded = () => browser.executeScript(() => {
      return window._expanded
    })
    await $('input').click()
    await expect(await lastEmittedExpanded()).toMatch(/true/i)
    await $('body').click()
    await expect(await lastEmittedExpanded()).toMatch(/false/i)
  })
```

a working test. executeScript callback is run in the browser, while the test is run in node.js and it is difficult to share values.

**Comment by eirikbacker** [comment]
Solves what use case/issue? :)

**Comment by astokke** [comment]
We have a hidden wrapper containing an input field and a core-suggest element.

The wrapper is shown and input field focused by a clicking a button. When core-suggest is closed we want to hide the wrapper and focus the button. We can listen to suggest.expanded to know when we should hide the wrapper.

**Comment by astokke** [comment]
Another suggestion would be a suggest.cancel event emitted when the user closes core-suggest without making a selection.

**Comment by eirikbacker** [comment]
@astokke Why don't you just style the input to look like an button, and expand on focus like demo 2 here? https://codepen.io/912lab/pen/LsplC

**Comment by astokke** [comment]
We will try using the existing implementation, so I'm closing this pull request.

**Pull request closed without merging**
