### PR TITLE
Feature/120 core scroll throttle

### LINKED ISSUE #120: core-scroll: throttling and customized timeout
Currently the `throttle` function used in `core-scroll` is more of a `debounce` function (except that it gives an initial event). `core-scroll` should use throttling as is specified in the documentation.

A request to customize the timeout for the throttle function in `core-scroll` has been issued by the kurator team. We should consider if this is necessary to implement or if changing to a proper throttling method is sufficient.

### PR DESCRIPTION
**Pull request by wwalmnes**
Resolves #120

### CODE REVIEW

**Comment by eirikbacker** [comment]
What is the use case? :)

**Comment by wwalmnes** [comment]
The Kurator team uses `core-scroll` in conjunction with a pagination indicator. The previous solution debounced the `scroll` event which resulted in the pagination not being updated while scrolling through the "pages". The new throttling allows them to have the pagination be in sync with the scrolling :).

Also 500ms seemed to give a slight delay to the experience, however when changing it to 100/200 ms there was no delay while retaining 60fps rendering. I believe the consumer should be able to determine what delay/interval they should use with regards to performance on their product.

**Comment by eirikbacker** [comment]
Also, how many DOM elements was used in the test page and did you check performance on both desktop and mobile? :)

**Comment by eirikbacker** [comment]
Please also add release notes and update documentation when releasing :)

**Comment by wwalmnes** [comment]
Using the native scroll event might be sufficient. @aevare or @erlingj would the native scroll event work for you :)? @eirikbacker considering that `scroll.change` is an event we provide that occurs when scrolling, meaning consumers might have an interest in the data it provides, should they not be able to decide the frequency of the data as well? It defaults to 500ms (the previous static value) if consumers does not make a conscious decision to change it.

Not many DOM elements were used in our simple test. We did check desktop and mobile which had seemingly good performance. This is absolutely something we can do further testing on and perhaps even automate so that new releases will also be continuously checked on performance :).

> Please also add release notes and update documentation when releasing :)

Will do!

**Comment by erlingj** [comment]
We can use the native scroll event instead, iz ok! We chose to use core-scroll's scroll event because it seemed like the natural thing to do. But we don't have to. This PR was made because the throttle is actually a debounce, and the fixed MS timeout made it difficult for us to use.

**Comment by eirikbacker** [comment]
I think also you have mistaken throttle vs. debounce - what was implemented is a throttle, what you added is a debounce :) Yes - rather update the documentation 👍

**Pull request merged**
